[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#242424"
foreground = "#ffffff"

[font]
size = 13.0

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Alt"

[selection]
save_to_clipboard = true
