#!/bin/bash
# i3 panel config. Powerline style.

panel_fifo="/tmp/i3_lemonbar_${USER}"
geometry="x14"
font="-xos4-terminesspowerline-medium-r-normal--12-120-72-72-c-60-iso10646-1"
iconfont="-xos4-terminusicons2mono-medium-r-normal--12-120-72-72-m-60-iso8859-1"
res_w=$(xrandr | grep "current" | awk '{print $8a}')
snd_cha=$(amixer get Master | grep "Playback channels:" | awk '{if ($4 == "") {printf "%s: Playback", $3} else {printf "%s %s: Playback", $3, $4}}')

# Enable/disable features
gmail_enable=false
irc_enable=false
mpd_enable=false
cmus_enable=true
battery_enable=true
volume_enable=true
disk_home_enable=true
disk_root_enable=true
network_enable=true
cpu_enable=true
memory_enable=true
date_enable=true
time_enable=true

# Alarm settings
cpu_alert=75                        # % cpu use
net_alert=5                         # K net use

# update setting, in seconds (conky update in i3_lemonbar_conky
upd_mail=300                        # Mail check update
upd_mpd=5                           # MPD song update
upd_cmus=0 							# Cmus song update

# color definitions
color_white="#FFFFFF";
color_black="#000000";

color_back="#FF1D1F21"              # Default background
color_fore="#FFC5C8C6"              # Default foreground
color_head="#FFB5BD68"              # Background for first element
color_sec_b1="#FF282A2E"            # Background for section 1
color_sec_b2="#FF454A4F"            # Background for section 2
color_sec_b3="#FF60676E"            # Background for section 3
color_icon="#FF979997"              # For icons
color_mail="#FFCE935F"              # Background color for mail alert
color_chat="#FFCC6666"              # Background color for chat alert
color_cpu="#FF5F819D"               # Background color for cpu alert
color_net="#FF5E8D87"               # Background color for net alert
color_bat="$color_sec_b2" 			# Background color for battery segment
color_music_bg="#1d2e7a" 	 		# Background color for music elements
color_music_fg="$color_white" 		# Background color for music elements
color_disable="#FF1D1F21"           # Foreground for disable elements
color_store_b1="$color_sec_b1";
color_net_b1="#871d1d";
color_sys_b1="#06513c";
color_wsp="#FF8C9440"               # Background for selected workspace

#default space between sections
if [ ${res_w} -gt 1024 ]; then
  stab='  '
else
  stab=' '
fi

# Char glyps for powerline fonts
sep_left=""                        # Powerline separator left
sep_right=""                       # Powerline separator right
sep_l_left=""                      # Powerline light separator left
sep_l_right=""                     # Powerline light sepatator right

# Icon glyphs from Terminusicons2
# TO TYPE MORE ICONS:
# Open the font file (~/.fonts/misc/terminusicons2mono.bcf) with any bdf editor (bdfedit)
# Find the icon you want and convert its number (i.e. 'A' is 65) to hexadecimal.
# In vim, type ^Vu and the 4 digit hexadecimal code
icon_clock="Õ"                      # Clock icon
icon_cpu="Ï"                        # CPU icon
icon_mem="Þ"                        # MEM icon
icon_dl="Ð"                         # Download icon
icon_ul="Ñ"                         # Upload icon
icon_vol="Ô"                        # Volume icon
icon_hd="À"                         # HD / icon
icon_home="Æ"                       # HD /home icon
icon_mail="Ó"                       # Mail icon
icon_chat="Ò"                       # IRC/Chat icon
icon_music="Î"                      # Music icon
icon_music_play="³"
icon_music_pause="²"
icon_music_stop="±"
icon_prog="Â"                       # Window icon
icon_contact="Á"                    # Contact icon
# icon_wired="Å" 					# Wired conection icon
icon_wired="" 					# Wired conection icon
icon_wifi="Ø" 						# Wifi icon
# icon_wsp="É"                        # Workspace icon
icon_wsp="Ç"                        # Workspace icon
icon_charging="" 				# Battery icon when charging
icon_battery="" 				# Battery icon when not charging
