-- =============================================================================
-- Generated by lightline to lualine theme converter
--   https://gist.github.com/shadmansaleh/000871c9a608a012721c6acc6d7a19b9
-- License: MIT License
-- =============================================================================

local colors = {
  color7   = "#c5c8c6",
  color8   = "#555555",
  color9   = "#81a2be",
  color10  = "#a0a0a0",
  color11  = "#b294bb",
  color14  = "#de935f",
  color0   = "#909090",
  color1   = "#434343",
  color2   = "#666666",
  color3   = "#1d1f21",
  color4   = "#b5bd68",
}

local Tomorrow_Night = {
  inactive = {
    a = { fg = colors.color0, bg = colors.color1 , gui = "bold", },
    c = { fg = colors.color0, bg = colors.color1 },
    b = { fg = colors.color2, bg = colors.color3 },
  },
  insert = {
    a = { fg = colors.color1, bg = colors.color4 , gui = "bold", },
    b = { fg = colors.color7, bg = colors.color8 },
  },
  normal = {
    a = { fg = colors.color1, bg = colors.color9 , gui = "bold", },
    c = { fg = colors.color10, bg = colors.color1 },
    b = { fg = colors.color7, bg = colors.color8 },
  },
  visual = {
    a = { fg = colors.color1, bg = colors.color11 , gui = "bold", },
    b = { fg = colors.color7, bg = colors.color8 },
  },
  replace = {
    a = { fg = colors.color1, bg = colors.color14 , gui = "bold", },
    b = { fg = colors.color7, bg = colors.color8 },
  },
}

return Tomorrow_Night