# and them some ls aliases
alias s='ls -CF'
alias l='ls -CF'
alias lsw='ls'
alias ll='ls -lh'
alias la='ls -A'
alias lla='ls -lhA'

# always get colorized grep
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# and assume we got permission to reboot without password
alias reboot='sudo reboot now'
alias shutdown='sudo shutdown now'
alias poweroff='sudo poweroff'

# and some custom aliases too
alias :q='exit'
alias ,,='cd ..'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ......='cd ../../../../../'
alias .......='cd ../../../../../../'
alias ........='cd ../../../../../../../'
alias .3='...'
alias .4='....'
alias .5='.....'
alias .6='......'
alias .7='.......'
alias .8='........'
alias 3.='.3'
alias 4.='.4'
alias 5.='.5'
alias 6.='.6'
alias 7.='.7'
alias 8.='.8'
alias aliases='$EDITOR $HOME/.bash_aliases'
alias ax='chmod a+x'
alias android='/usr/share/android-studio/bin/studio.sh > /dev/null 2> /dev/null &'
alias bat='battery'
alias battery='upower -i /org/freedesktop/UPower/devices/battery_BAT0| grep -E "state|time\ to\ full|percentage"'
alias bashrc='$EDITOR $HOME/.bashrc'
alias buildjava='rm *.class && javac *.java && java Main'
alias c='cd'
alias cdshared='cd ~/Drive/Apuntes/IA/Practicas/IA/'
alias checkbash='changed=false; for name in .bashrc .bash_aliases .bash_functions; do $(cmp -s ~/$name ~/Shared/$name) || (meld ~/$name ~/Shared/$name && changed=true); done; $changed || echo "Nothing to check"; unset changed;'
alias chrome='google-chrome-stable > /dev/null 2> /dev/null &'
alias cl='fc -e -|pbcopy' # Copy the output of last command to clipboard
alias clean='sudo pacman -Scc && sudo pacman -Rs $(pacman -Qqtd) && rmshit'
alias clera='clear'
alias clipcp='xsel --clipboard <'
alias clippaste='xsel --clipboard >>'
alias cls='reset'
alias connection='ping -c 3 www.google.com'
alias cp='cp -v'
alias cpw7='cpvm Windows7'
alias cpxp='cpvm XP'
alias dd='sudo dd status=progress'
alias depth='echo $(($(find . | tr -cd "/\n" | sort | tail -1 | wc -c) -1))'
alias diff='colordiff'
alias dotfiles='git clone https://github.com/ocaballeror/dotfiles.git'
alias eclipse='/opt/eclipse/eclipse > /dev/null 2> /dev/null &'
alias files='find . -type f | wc -l'
alias fucking='sudo'
alias fuckyou='sudo'
alias functions='vim ~/.bash_functions'
alias gdrive='sudo gdfs -o big_writes -o allow_other /home/$USER/.config/gdfs/gdfs.auth /media/$USER/gdfs'
#alias github='git clone https://github.com/ocaballeror/laughing-goggles.git'
alias g++='g++ -std=c++14'
alias hask='ghci'
alias haskell='ghci'
alias indigo='/opt/eclipse-indigo/eclipse > /dev/null 2> /dev/null &'
alias lsç='ls'
alias lslbk='lsblk'
alias less='less -r'                          # raw control characters
alias mdkir='mkdir'
alias mega='megasync > /dev/null 2> /dev/null &'
alias mem='free -mlt'
alias mkdir='mkdir -p'
alias mount='sudo mount'
alias mroe='more'
alias mv='mv -v'
alias mydu='du -hcs .[!.]* * 2> /dev/null | sort -hr | more'
alias mydu2='du -hcs .[!.]* */* 2> /dev/null | sort -hr | more'
alias mydu3='du -hcs .[!.]* */*/* 2> /dev/null | sort -hr | more'
alias mydu4='du -hcs .[!.]* */*/*/* 2> /dev/null | sort -hr | more'
alias mydu5='du -hcs .[!.]* */*/*/*/* 2> /dev/null | sort -hr | more'
alias ny='vpn US_New_York_City'
alias path='echo $PATH'
alias pkill='pkill -e'
alias protege='/opt/Protege/Protege > /dev/null 2> /dev/null &'
alias publicip='ip="$(wget https://ipinfo.io/ip -qO -)"; loc="$(wget http://ipinfo.io/city -qO -)"; [ -z $loc ] && loc="$(wget http://ipinfo.io/country -qO -)"; echo -n "$ip"; [ -n $loc ] && echo "-- $loc" || echo ""; unset ip; unset loc'
alias quit='exit'
alias quti='quit'
alias receivebash='receivedots'
#alias receivedots='for dot in bashrc bash_aliases bash_functions vimrc tmux.conf; do cp ~/Shared/.$dot ~; done; reload'
alias receivedots='git clone https://github.com/ocaballeror/dotfiles.git && for file in $(find dotfiles -mindepth 2 | grep -v .git); do cp $file ~; done; rm -rf dotfiles'
alias reload='source $HOME/.bashrc'
alias sduo='sudo'
alias sever='server'
alias sl='ls'
alias speedtest='wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip'
alias src='nano ~/.bashrc'
alias sshphone='ssh root@192.168.1.39'
alias sshrasp='ssh pi@192.168.1.121; [ $? != 0 ] && ssh pi@192.168.1.120'
alias sshrasp2='ssh pi@192.168.1.125'
alias sshtfg='tfg-nfc@taiga.dacya.ucm.es'
alias start='vpn && drive && cd -'
alias sulb='subl'
alias swipl.='swipl'
alias trash='gvfs-trash'
alias umount='sudo umount'
#alias update='sudo apt-get clean && sudo apt-get update && sudo apt-get autoremove && sudo apt-get upgrade'
alias update='yaourt -Syu --devel --aur --noconfirm'
alias fullupdate='yaourt -Syu --devel --aur --noconfirm && yaourt -Syu --devel --aur'
alias vimrc='$EDITOR ~/.vimrc'
alias vms='cd /media/$USER/Data/Software/VirtualBoxVMs/'
alias watchbat='while true; do bat; sleep 1; clear; done'
alias watchip='watch "wget https://ipinfo.io/ip -qO -"'
alias whence='type -a'                        # where, of a sort
alias wireshark='sudo wireshark-gtk > /dev/null 2> /dev/null &'
